# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - image: registry.ng.bluemix.net/quan_thinklabs/nginx
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
      dnsPolicy: ClusterFirst
